config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  root to: 'questions#index'

  get '/search', to: 'search#search'

  concern :votable do
    member do
      patch :like
      patch :dislike
      patch :reset
    end
  end

  concern :commentable do
    member { post :create_comment }
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, shallow: true, concerns: [:votable, :commentable], except: :index do
      patch 'best', on: :member
    end
    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, :others, on: :collection
      end
      resources :questions, only: [:index, :show, :create, :update, :destroy] do
        resources :answers, shallow: true, only: [:show, :create, :update, :destroy]
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Linkable
  include Fileable
  include Authorable
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_one :reward, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user

  accepts_nested_attributes_for :reward, reject_if: :all_blank, allow_destroy: true

  validates :title, :body, presence: true

  scope :past_day, -> { where(created_at: (Time.current.yesterday.beginning_of_day..Time.current.yesterday.end_of_day)) }

  def subscription(user)
    subscriptions.where(user: user).first
  end

  def subscribe!(user)
    subscriptions.create(user: user) unless subscription(user)
  end

  def unsubscribe!(user)
    subscription(user)&.destroy!
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  load_and_authorize_resource

  def index
    render json: questions
  end

  def show
    render json: @question
  end

  def create
    @question = current_resource_owner.questions.new(question_params)
    if @question.save
      render json: @question
    else
      head :unprocessable_entity
    end
  end

  def update
    if @question.update(question_params)
      render json: @question
    else
      head :unprocessable_entity
    end
  end

  def destroy
    @question.destroy
    render json: questions
  end

  private

  def questions
    Question.all
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted
  include Commented

  before_action :authenticate_user!, except: %i[index show]
  before_action :load_question, only: %i[show edit update destroy]
  after_action :publish_question, only: %i[create]

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
    @answers = @question.answers
    @answer.links.new
    @comments = @question.comments
    gon.question_id = @question.id
    gon.answer_ids = @question.answers.map { |answer| answer.id }
  end

  def new
    @question = Question.new
    @question.links.new
    @question.reward = Reward.new
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      @question.subscribe!(current_user)
      redirect_to @question, notice: 'Your question has been successfully created.'
    else
      flash.now[:notice] = 'Something went wrong.'
    end
  end

  def edit
  end

  def update
    @question.update(question_params)
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: 'Your question has been deleted.'
  end

  private

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast('questions',
                                 ApplicationController.render(partial: 'questions/question_title',
                                                              locals: { question: @question }))
  end

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [],
                                                    links_attributes: [:name, :url, :_destroy],
                                                    reward_attributes: [:title, :badge])
  end
end

app/views/questions/_question.html.slim
h1= question.title
p class='body'
  = question.body

- if can?(:edit, question) && question.reward.present?
  p Reward
  ul
    li= question.reward.title
    li= image_tag question.reward.badge

- unless question.links.empty?
  .links
    p Links:
    ul
      - question.links.each do |link|
        - if link.gist?
          li
            p= link_to link.gist_fetch_content, link.url
            - if can?(:edit, question)
              p= link_to 'Delete link', link_path(link), method: :delete, remote: true
        - else
          li
            p= link_to link.name, link.url, target: :_blank, data: { confirm: "Are you sure?" }
            - if can?(:edit, question)
              p= link_to 'Delete link', link_path(link), method: :delete, remote: true

- if question.files.attached?
  - question.files.each do |file|
    p= link_to file.filename.to_s, url_for(file)
    - if can?(:edit, question)
      p= link_to 'Delete file', attachment_path(file), method: :delete, remote: true

- if can?(:edit, question) && user_signed_in?
  p= link_to 'Edit', '#', class: 'edit-question-link', data: { question_id: question.id }
  p= link_to 'Delete question', question_path(question), method: :delete, remote: true

  = form_with model: question, class: 'hidden', html: {id: "edit-question-#{question.id}"} do |f|
    b= f.label :title, "Edit title:"
    br
    = f.text_field :title
    br
    b= f.label :body, "Edit question:"
    br
    = f.text_area :body
    br
    br
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
    br
    = f.fields_for :links do |l|
      = render 'shared/link_fields', f: l
    br
    .links
      = link_to_add_association 'Add link', f, :links, partial: 'shared/link_fields'
    br
    = f.submit 'Update question'

app/views/questions/_question_title.html.slim
= link_to question.title, question

app/views/questions/create.js.erb
<% if alert %>
$('.flash').html('<p class="alert"><%= alert %></p>');
<% end %>

<% if notice %>
$('.flash').html('<p class="notice"><%= notice %></p>');
<% end %>

$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');

app/views/questions/index.html.slim
- if can?(:create, Question)
  p= link_to 'Ask question', new_question_path

.questions-list
  br
  b List of available questions:
  br
  - cache collection_cache_key_for :question  do
    - @questions.each do |question|
      p= link_to question.title, question

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

.question-errors

h2 class='header'
  ' Ask a question:

= form_with model: @question do |f|
  = f.label :title, 'Title:'
  = f.text_field :title
  br
  br
  = f.label :body, 'Body:'
  = f.text_area :body
  br
  br
  = f.label :files, 'Files:'
  = f.file_field :files, multiple: true, direct_upload: true
  br
  br
  = f.fields_for :reward do |r|
    = r.label :title, 'Reward:'
    = r.text_field :title
    br
    br
    = r.label :badge, 'Badge:'
    = r.file_field :badge, direct_upload: true
  br
  br
  .links
    = link_to_add_association 'Add link', f, :links, partial: 'shared/link_fields'
  br
  = f.submit 'Ask'

p= link_to 'Back', questions_path

app/views/questions/show.html.slim
- cache @question do
  .question
    = render @question

  .question-voting
    .question-scores
      br
      | Scores: #{@question.scores}

    .question-voting-links
      = render 'shared/voting_links', resource: @question

.question-subscribe
  - if can?(:create, Subscription) && !@question.subscription(current_user)
    p= link_to 'Subscribe', question_subscriptions_path(@question), method: :post
  - if can?(:destroy, @question.subscription(current_user)) && @question.subscription(current_user)
    p= link_to 'Unsubscribe', subscription_path(@question.subscription(current_user)), method: :delete

.question-comments
  - if @comments.exists?
    - cache @comments do
      p Comments:
      = render @comments

.question-new-comment
  - if !current_user&.author_of?(@question) && user_signed_in?
    - cache @question do
      p= link_to 'Add comment', '#', class: 'comment-question-link', data: {question_id: @question.id}

      = render 'comments/comment_form', resource: @question

.question-errors

h3 Answers:
.no-answers-greetings
  - if @answers.empty?
    ' There is no answers. Be first!

- cache @answers do
  .answers
    = render @answers

.answer-errors

- if user_signed_in?
  br
  = form_with model: [@question, @answer], class: 'new-answer' do |f|
    br
    b= f.label :body, "Your answer:"
    br
    = f.text_area :body
    br
    br
    = f.label :files, "Files: "
    = f.file_field :files, multiple: true
    br
    br
    .links
      = link_to_add_association 'Add link', f, :links, partial: 'shared/link_fields'
    br
    = f.submit 'Post answer'

app/views/questions/update.js.erb
<% if alert %>
$('.flash').html('<p class="alert"><%= alert %></p>');
<% end %>

<% if notice %>
$('.flash').html('<p class="notice"><%= notice %></p>');
<% end %>

$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');
<% unless @question.errors.present? %>
  $('.question').html('<%= j render @question %>');
<% end %>