config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  root to: 'questions#index'

  get '/search', to: 'search#search'

  concern :votable do
    member do
      patch :like
      patch :dislike
      patch :reset
    end
  end

  concern :commentable do
    member { post :create_comment }
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, shallow: true, concerns: [:votable, :commentable], except: :index do
      patch 'best', on: :member
    end
    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, :others, on: :collection
      end
      resources :questions, only: [:index, :show, :create, :update, :destroy] do
        resources :answers, shallow: true, only: [:show, :create, :update, :destroy]
      end
    end
  end
end

app/views/shared/403.js.erb
$('.errors').html(<%= "Error #{status}:  #{message}" %>)

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_header.html.slim
h1[class='header']
  = link_to "QnA", root_url
- if !user_signed_in?
  = link_to "Log in", new_user_session_path
  '  or
  = link_to "Sign up", new_user_registration_path
- if user_signed_in?
  ' Hello,
  b= "#{current_user.email}"
  br
  = link_to "Log out", destroy_user_session_path, method: :delete
  br
  = link_to 'Rewards', rewards_path
  br
  = render 'search/form'
  br

app/views/shared/_link_fields.html.slim
.nested-fields
  .field
    = f.label :name, 'Link name:'
    = f.text_field :name
  br
  .field
    =f.label :url, 'URL:'
    =f.text_field :url
  br
  = link_to_remove_association 'Remove link fields', f
  br
  br

app/views/shared/_voting_links.html.slim
- if user_signed_in? && !current_user.author_of?(resource)
  p = link_to "Like", polymorphic_path(resource, action: :like), method: :patch, data: { type: :json }, remote: true unless resource.voted?(current_user)
  p = link_to "Dislike", polymorphic_path(resource, action: :dislike), method: :patch, data: { type: :json }, remote: true unless resource.voted?(current_user)
  p = link_to 'Reset', polymorphic_path(resource, action: :reset), method: :patch, data: { type: :json }, remote: true if resource.voted?(current_user)