config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  root to: 'questions#index'

  get '/search', to: 'search#search'

  concern :votable do
    member do
      patch :like
      patch :dislike
      patch :reset
    end
  end

  concern :commentable do
    member { post :create_comment }
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, shallow: true, concerns: [:votable, :commentable], except: :index do
      patch 'best', on: :member
    end
    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, :others, on: :collection
      end
      resources :questions, only: [:index, :show, :create, :update, :destroy] do
        resources :answers, shallow: true, only: [:show, :create, :update, :destroy]
      end
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Linkable
  include Fileable
  include Authorable
  include Votable
  include Commentable

  belongs_to :question, touch: true

  validates :body, presence: true

  after_create :do_question_subscription_job

  default_scope { order(best: :desc, updated_at: :desc) }

  def set_best
    transaction do
      question.answers.where(best: true).update_all(best: false)
      update!(best: true)
      question.reward.update!(user: author) if question.reward.present? && !question.author.author_of?(self)
    end
  end

  private

  def do_question_subscription_job
    QuestionSubscriptionJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted
  include Commented

  before_action :authenticate_user!, except: %i[show]
  before_action :load_question, only: %i[new create]
  before_action :load_answer, only: %i[show destroy update best]
  after_action :publish_answer, only: %i[create]

  authorize_resource

  def show
  end

  def new
    @answer = @question.answers.new
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.author = current_user

    if @answer.save
      flash.now[:notice] = 'Your answer has been successfully created.'
    else
      flash.now[:notice] = 'Something went wrong.'
    end
  end

  def destroy
    @answer.destroy
    redirect_to question_path(@answer.question), notice: 'Your answer has been deleted.'
  end

  def update
    @answer.update(answer_params)
    @question = @answer.question
  end

  def best
    @answer.set_best
  end

  private

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast("answers_for_question_#{@question.id}",
                                 answer: @answer, links: @answer.links.to_a, files: @answer.files_params)
  end

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [],
                                          links_attributes: [:name, :url, :_destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  load_and_authorize_resource

  before_action :load_question, only: :create

  def show
    render json: @answer
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.author = current_resource_owner
    if @answer.save
      render json: @question
    else
      head :unprocessable_entity
    end
  end

  def update
    if @answer.update(answer_params)
      render json: @answer
    else
      head :unprocessable_entity
    end
  end

  def destroy
    @answer.destroy
    render json: @question
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/views/answers/_answer.html.slim
div[class="answer-#{answer.id}" style="border-top: 1px solid #F0F0F0;"]
  p class='body'
    = answer.body

  .answer-voting
    p.answer-scores
      | Scores: #{answer.scores}

    .answer-voting-links
      = render 'shared/voting_links', resource: answer

  - unless answer.links.empty?
    .links
      p Links:
      ul
        - answer.links.each do |link|
          - if link.gist?
            li
              p= link_to link.gist_fetch_content, link.url
              - if can?(:edit, answer)
                p= link_to 'Delete link', link_path(link), method: :delete, remote: true
          - else
            li
              p= link_to link.name, link.url, target: :_blank, data: { confirm: "Are you sure?" }
              - if can?(:edit, answer)
                p= link_to 'Delete link', link_path(link), method: :delete, remote: true

  - if answer.files.attached?
    - answer.files.each do |file|
      p= link_to file.filename.to_s, url_for(file)
      - if can?(:edit, answer)
        p= link_to 'Delete file', attachment_path(file), method: :delete, remote: true

  - if user_signed_in?
    - if can?(:edit, answer)
      p= link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
      p= link_to 'Delete answer', answer_path(answer), method: :delete
    - if current_user&.author_of?(answer.question) && !answer.best?
      p= link_to 'Mark as the best', best_answer_path(answer), method: :patch, remote: true

  .answer-comments
    - if answer.comments.exists?
      p Comments:
      = render answer.comments

  .answer-new-comment
    - if !current_user&.author_of?(answer) && user_signed_in?
      p= link_to 'Add comment', '#', class: 'comment-answer-link', data: {answer_id: answer.id}

      = render 'comments/comment_form', resource: answer

  = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
    b= f.label :body, 'Edit answer:'
    br
    = f.text_area :body
    br
    br
    = f.label :files, 'Files:'
    = f.file_field :files, multiple: true, direct_upload: true
    br
    = f.fields_for :links do |l|
      = render 'shared/link_fields', f: l
    br
    .links
      = link_to_add_association 'Add link', f, :links, partial: 'shared/link_fields'
    br
    = f.submit 'Update answer'

app/views/answers/best.js.erb
$('.answers').html('<%= j render @answer.question.answers %>');

app/views/answers/create.js.erb
<% if alert %>
  $('.flash').html('<p class="alert"><%= alert %></p>');
<% end %>

<% if notice %>
  $('.flash').html('<p class="notice"><%= notice %></p>');
<% end %>

$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');
$('.no-answers-greetings').addClass('hidden');
<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/update.js.erb
<% if alert %>
$('.flash').html('<p class="alert"><%= alert %></p>');
<% end %>

<% if notice %>
$('.flash').html('<p class="notice"><%= notice %></p>');
<% end %>

$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');
<% unless @answer.errors.present? %>
  $('.answer-<%= @answer.id %>').html('<%= j render @answer %>');
  $('.new-answer').show();
<% end %>